// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tracklete-condensed/Homepage.tsx": () => import("../components/mockups/tracklete-condensed/Homepage.tsx"),
  "./components/mockups/tracklete-home/Homepage.tsx": () => import("../components/mockups/tracklete-home/Homepage.tsx"),
  "./components/mockups/tracklete-jakarta/Homepage.tsx": () => import("../components/mockups/tracklete-jakarta/Homepage.tsx")
};
